FROM nginx:1.25.3-alpine
LABEL maintainer="jacksonantunes <jackson.antunes.sampaio@gmail.com>"
COPY . /usr/share/nginx/html
EXPOSE 80
# docker run --name "servidor_web" -d -p 8080:80 jacksonantunes/servidor_web:v1